//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dodatna_aktivnost
    {
        public dodatna_aktivnost()
        {
            this.rezervacija = new HashSet<rezervacija>();
        }
    
        public int dodatna_aktivnost_id { get; set; }
        public string naziv { get; set; }
        public System.DateTime datumvrijeme_pocetka { get; set; }
        public System.DateTime datumvrijeme_zavrsetka { get; set; }
        public double cijena { get; set; }
        public int putovanje_FK { get; set; }
    
        public virtual putovanje putovanje { get; set; }
        public virtual ICollection<rezervacija> rezervacija { get; set; }
    }
}
