//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PogledRezervacijaDodatnihAktivnosti
    {
        public int rezervacija_id { get; set; }
        public int dodatne_aktivnosti_id { get; set; }
    }
}
