//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijevozno_poduzece
    {
        public prijevozno_poduzece()
        {
            this.putovanje = new HashSet<putovanje>();
        }
    
        public int prijevozno_poduzece_id { get; set; }
        public string naziv { get; set; }
        public int broj_sjedala { get; set; }
        public string vrsta_prijevoza { get; set; }
    
        public virtual ICollection<putovanje> putovanje { get; set; }
    }
}
