//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijava
    {
        public int prijava_id { get; set; }
        public System.DateTime datumvrijeme_prijava { get; set; }
        public int zaposlenik_FK { get; set; }
    
        public virtual zaposlenik zaposlenik { get; set; }
    }
}
