//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class putnik
    {
        public putnik()
        {
            this.rezervacija = new HashSet<rezervacija>();
        }
    
        public int putnik_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string kontakt { get; set; }
    
        public virtual ICollection<rezervacija> rezervacija { get; set; }
    }
}
