//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class putovanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public putovanje()
        {
            this.dodatna_aktivnost = new HashSet<dodatna_aktivnost>();
            this.rezervacija = new HashSet<rezervacija>();
        }
    
        public int putovanje_id { get; set; }
        public System.DateTime datumvrijeme_polaska { get; set; }
        public System.DateTime datumvrijeme_povratka { get; set; }
        public int broj_osoba { get; set; }
        public double cijena { get; set; }
        public int zaposlenik_FK { get; set; }
        public int prijevozno_poduzece_FK { get; set; }
        public int destinacija_FK { get; set; }
        public string naziv { get; set; }
    
        public virtual destinacija destinacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dodatna_aktivnost> dodatna_aktivnost { get; set; }
        public virtual prijevozno_poduzece prijevozno_poduzece { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervacija> rezervacija { get; set; }
    }
}
