//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class racun
    {
        public int racun_id { get; set; }
        public int zaposlenik_FK { get; set; }
        public System.DateTime datumvrijeme_izdavanja { get; set; }
        public double ukupna_cijena { get; set; }
        public int rezervacija_FK { get; set; }
    
        public virtual rezervacija rezervacija { get; set; }
    }
}
