//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezervacija
    {
        public rezervacija()
        {
            this.racun = new HashSet<racun>();
            this.dodatna_aktivnost = new HashSet<dodatna_aktivnost>();
        }
    
        public int rezervacija_id { get; set; }
        public int putovanje_FK { get; set; }
        public int putnik_FK { get; set; }
    
        public virtual putnik putnik { get; set; }
        public virtual putovanje putovanje { get; set; }
        public virtual ICollection<racun> racun { get; set; }
        public virtual ICollection<dodatna_aktivnost> dodatna_aktivnost { get; set; }
    }
}
