//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenik
    {
        public zaposlenik()
        {
            this.prijava = new HashSet<prijava>();
            this.putovanje = new HashSet<putovanje>();
        }
    
        public int zaposlenik_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string kriptirana_lozinka { get; set; }
        public int razina_prava_FK { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<prijava> prijava { get; set; }
        public virtual ICollection<putovanje> putovanje { get; set; }
        public virtual razina_prava razina_prava { get; set; }
    }
}
