//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeTravel
{
    using DB;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesWeTravel : DbContext
    {
        public EntitiesWeTravel()
            : base("name=EntitiesWeTravel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<destinacija> destinacija { get; set; }
        public virtual DbSet<dodatna_aktivnost> dodatna_aktivnost { get; set; }
        public virtual DbSet<prijava> prijava { get; set; }
        public virtual DbSet<prijevozno_poduzece> prijevozno_poduzece { get; set; }
        public virtual DbSet<putnik> putnik { get; set; }
        public virtual DbSet<putovanje> putovanje { get; set; }
        public virtual DbSet<racun> racun { get; set; }
        public virtual DbSet<razina_prava> razina_prava { get; set; }
        public virtual DbSet<rezervacija> rezervacija { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<zaposlenik> zaposlenik { get; set; }
        public virtual DbSet<PogledRezervacijaDodatnihAktivnosti> PogledRezervacijaDodatnihAktivnosti { get; set; }
    }
}
